---
- name: Generate .rsc to recreate admin addr-list
  template: src=addr-list.rsc.j2 dest=roles/addr-list-admin/files/tmp/{{inventory_hostname}}.rsc

- name: Recreate admin addr-list
  command: bash -c "cat roles/addr-list-admin/files/tmp/{{inventory_hostname}}.rsc | ssh -T {{inventory_hostname}} -p {{ansible_ssh_port}}"

- name: Delete temp .rsc file
  file: path=roles/addr-list-admin/files/tmp/{{inventory_hostname}}.rsc state=absent
