---
#Initial router settings
- hosts: new_hosts
  gather_facts: no  
  connection: local
  roles:
    - add-to-ansible
    
  vars_prompt:
   - name: "ros_login"
     prompt: "Enter login"
     private: no
   
   - name: "ros_passwd"
     prompt: "Enter password"
     private: yes
