---
- name: Generate .rsc to add certs
  template: src=ovpn_client.rsc.j2 dest=roles/ovpn_client/files/tmp/{{inventory_hostname}}.rsc

- name: Copy certs to device
  copy:
    src: {{ovpn_cert_dir}}/{{item}}
    dest: /
    with_items:
      - "{{ovpn_cert_file}}"
      - "{{ovpn_key_file}}"
      - "{{ovpn_ca_file}}"

- name: Activate certs on device
  action: shell "cat roles/ovpn_client/files/tmp/{{inventory_hostname}}.rsc | ssh -T {{inventory_hostname}} -p {{ansible_ssh_port}}"

- name: Delete temp .rsc file
  file: path=roles/ovpn_client/files/tmp/{{inventory_hostname}}.rsc state=absent
