---
- name: Generate .rsc to set E-Mail options
  template: src=email-setup.rsc.j2 dest=roles/email-setup/files/tmp/{{inventory_hostname}}.rsc

- name: Email setup
  command: bash -c "cat roles/email-setup/files/tmp/{{inventory_hostname}}.rsc | ssh -T {{inventory_hostname}} -p {{ansible_ssh_port}}"

- name: Delete temp .rsc file
  file: path=roles/email-setup/files/tmp/{{inventory_hostname}}.rsc state=absent
