---
- name: Generate .rsc for change WiFi password
  template: src=script.rsc.j2 dest=roles/change-wifi-passwd/files/tmp/{{inventory_hostname}}.rsc

- name: Change WiFi Passwd
  command: bash -c "cat roles/change-wifi-passwd/files/tmp/{{inventory_hostname}}.rsc | ssh -T {{inventory_hostname}} -p {{ansible_ssh_port}}"

  - name: Delete temp .rsc file
    file: path=roles/change-wifi-passwd/files/tmp/{{inventory_hostname}}.rsc state=absent
